<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-06 at 06:54:14.
 */
class AdminAppliControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AdminAppliController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AdminAppliController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AdminAppliController::adminappli
     * @todo   Implement testAdminappli().
     */
    public function testAdminappli() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
