<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-06 at 06:55:05.
 */
class AdminDataControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AdminDataController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AdminDataController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AdminDataController::admindata
     * @todo   Implement testAdmindata().
     */
    public function testAdmindata() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
