<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-06 at 06:55:56.
 */
class ConnexionControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConnexionController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConnexionController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ConnexionController::connexion
     * @todo   Implement testConnexion().
     */
    public function testConnexion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConnexionController::redirect
     * @todo   Implement testRedirect().
     */
    public function testRedirect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
