<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-07 at 12:32:25.
 */
class ConnexionControllerTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var ConnexionController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConnexionController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers ConnexionController::connexion
     * @todo   Implement testConnexion().
     */
    public function testConnexion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


}
