<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-06 at 06:57:17.
 */
class HomeControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HomeController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HomeController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HomeController::home
     * @todo   Implement testHome().
     */
    public function testHome() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
