<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-06 at 06:49:54.
 */
class RouterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Router;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Router::home
     * @todo   Implement testHome().
     */
    public function testHome() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Router::administration
     * @todo   Implement testAdministration().
     */
    public function testAdministration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
